baseURL = 'https://yuraautsayder.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ga-hugo-theme'
[menus]
  [[menus.main]]
    name = 'Главная'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'О компании'
    url = '/about'
    weight = 20
  [[menus.main]]
    name = 'Docs'
    url = '/docs'
    weight = 30
