baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ga-hugo-theme'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "О компании"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "Посты"
    url = "/posts/"
    weight = 3
